services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./templates:/etc/nginx/templates
    environment:
      TZ: Asia/Shanghai
    logging:
      options:
        max-size: 20m
        max-file: 1

  mongo:
    image: mongo
    restart: always
    # ports:
    #   - 27017:27017
    volumes:
      - ./db:/data/db
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    logging:
      options:
        max-size: 20m
        max-file: 1

  express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    # ports:
    #   - 8081:8081
    environment:
      ME_CONFIG_SITE_BASEURL: /express/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017
    logging:
      options:
        max-size: 20m
        max-file: 1

  serve:
    depends_on:
      - mongo
    image: kalts/grass # ghcr.io/ciocoa/grass
    restart: always
    ports:
      - 443:443
      - 22102:22102/udp
    volumes:
      - ./plugins:/plugins
    environment:
      GC_TZ: Asia/Shanghai
      GC_LANGUAGE: zh_CN
      GC_ACCESS_ADDRESS: 127.0.0.1
      GC_BIND_PORT: 443
      GC_AUTO_CREATE: "true"
      GC_ENABLE_CONSOLE: "false"
      GC_MONGODB_URL: mongodb://root:123456@mongo:27017
    logging:
      options:
        max-size: 20m
        max-file: 1
