name: Gradle

on:
  pull_request:
    branches: [ 'origin' ]
  workflow_dispatch:

env:
  PLUGIN_PATH: plugin

permissions:
  contents: read
  packages: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout server
        uses: actions/checkout@v4
        with:
          ref: origin

      - name: Checkout plugin
        uses: actions/checkout@v4
        with:
          repository: jie65535/gc-opencommand-plugin
          path: ${{ env.PLUGIN_PATH }}

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build server
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar

      - name: Publish server
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish

      - name: Setup plugin
        run: cd ${{ env.PLUGIN_PATH }} && chmod +x gradlew && mkdir lib && mv ../grasscutter-*.jar lib

      - name: Build plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar
          build-root-directory: ${{ env.PLUGIN_PATH }}

      - name: Publish plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
          build-root-directory: ${{ env.PLUGIN_PATH }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: |
            *.jar
            ${{ env.PLUGIN_PATH }}/*.jar
