name: Gradle

on:
  push:
    branches: ["origin"]
  pull_request:
    branches: ["origin"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  # This is used to complete the identity challenge
  # with sigstore/fulcio when running outside of PRs.
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build

    steps:
      - name: Checkout server
        uses: actions/checkout@v4
        with:
          ref: origin

      - name: Checkout plugin
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.PLUGIN_REPO }}
          path: ${{ vars.PLUGIN_PATH }}

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build server
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar

      # - name: Publish server
      #   uses: gradle/gradle-build-action@v2
      #   with:
      #     arguments: publish

      - name: Setup lib
        run: |
          cd ${{ vars.PLUGIN_PATH }}
          chmod +x gradlew
          mkdir lib
          cp ../*.jar lib

      - name: Build plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar
          build-root-directory: ${{ vars.PLUGIN_PATH }}

      # - name: Publish plugin
      #   uses: gradle/gradle-build-action@v2
      #   with:
      #     arguments: publish
      #     build-root-directory: ${{ vars.PLUGIN_PATH }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: |
            *.jar
            ${{ vars.PLUGIN_PATH }}/*.jar

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment: build

    steps:
      - name: Checkout dockerfile
        uses: actions/checkout@v4

      - name: Checkout resources
        run: wget -q ${{ vars.RESOURCES_REPO }} -O archive.zip

      - name: Download artifact
        uses: actions/download-artifact@v3

      - name: Install cosign
        if: github.event_name != 'pull_request' && github.event_name == 'push'
        uses: sigstore/cosign-installer@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into ${{ vars.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.REGISTRY }}/${{ github.repository }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        if: github.event_name != 'pull_request' && github.event_name == 'push'
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
